// <auto-generated />
using System;
using AspNetCoreApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore.Migrations.Library_Db
{
    [DbContext(typeof(Library_DbContext))]
    [Migration("20251121084135_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreApp.Models.Library_DocumentDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("HasImage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedVersionsId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("_integrityVersion")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("RelatedVersionsId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ElementDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasColumnType("longtext");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("ParentDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentDocumentId");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_LibraryDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("HasImage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("_integrityVersion")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_OwnerDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultLibraryGuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DefaultShelfGuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_RelatedVersionsDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("RelatedVersions");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ShelfDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("HasImage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<byte>("_integrityVersion")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Shelves");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_TagDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Library_DocumentDbModelLibrary_ShelfDbModel", b =>
                {
                    b.Property<int>("DocumentsId")
                        .HasColumnType("int");

                    b.Property<int>("ParentShelvesId")
                        .HasColumnType("int");

                    b.HasKey("DocumentsId", "ParentShelvesId");

                    b.HasIndex("ParentShelvesId");

                    b.ToTable("Library_DocumentDbModelLibrary_ShelfDbModel");
                });

            modelBuilder.Entity("Library_DocumentDbModelLibrary_TagDbModel", b =>
                {
                    b.Property<int>("DocumentsId")
                        .HasColumnType("int");

                    b.Property<int>("TagsId")
                        .HasColumnType("int");

                    b.HasKey("DocumentsId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("Library_DocumentDbModelLibrary_TagDbModel");
                });

            modelBuilder.Entity("Library_LibraryDbModelLibrary_ShelfDbModel", b =>
                {
                    b.Property<int>("ParentLibrariesId")
                        .HasColumnType("int");

                    b.Property<int>("ShelvesId")
                        .HasColumnType("int");

                    b.HasKey("ParentLibrariesId", "ShelvesId");

                    b.HasIndex("ShelvesId");

                    b.ToTable("Library_LibraryDbModelLibrary_ShelfDbModel");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_DocumentDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "Owner")
                        .WithMany("Documents")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_RelatedVersionsDbModel", "RelatedVersions")
                        .WithMany("Documents")
                        .HasForeignKey("RelatedVersionsId");

                    b.Navigation("Owner");

                    b.Navigation("RelatedVersions");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ElementDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "Owner")
                        .WithMany("Elements")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_DocumentDbModel", "ParentDocument")
                        .WithMany("Elements")
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ParentDocument");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_LibraryDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "Owner")
                        .WithMany("Libraries")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ShelfDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "Owner")
                        .WithMany("Shelves")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Library_DocumentDbModelLibrary_ShelfDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_DocumentDbModel", null)
                        .WithMany()
                        .HasForeignKey("DocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_ShelfDbModel", null)
                        .WithMany()
                        .HasForeignKey("ParentShelvesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Library_DocumentDbModelLibrary_TagDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_DocumentDbModel", null)
                        .WithMany()
                        .HasForeignKey("DocumentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_TagDbModel", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Library_LibraryDbModelLibrary_ShelfDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_LibraryDbModel", null)
                        .WithMany()
                        .HasForeignKey("ParentLibrariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_ShelfDbModel", null)
                        .WithMany()
                        .HasForeignKey("ShelvesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_DocumentDbModel", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_OwnerDbModel", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Elements");

                    b.Navigation("Libraries");

                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_RelatedVersionsDbModel", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
