// <auto-generated />
using System;
using AspNetCoreApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore.Migrations.Library_Db
{
    [DbContext(typeof(Library_DbContext))]
    partial class Library_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreApp.Models.Library_DocumentDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("HasImage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("RelatedVersionsId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<byte>("_integrityVersion")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("RelatedVersionsId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_DocumentTag_DbModel", b =>
                {
                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("DocumentId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("DocumentTags");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ElementDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int>("ParentDocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<byte>("_order")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.HasIndex("ParentDocumentId");

                    b.HasIndex("UpdatedAt");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_FollowerFollowing_DbModel", b =>
                {
                    b.Property<int>("FollowerId")
                        .HasColumnType("int");

                    b.Property<int>("FollowingId")
                        .HasColumnType("int");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("FollowerFollowings");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_LibraryDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("HasImage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<byte>("_integrityVersion")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_LibraryShelf_DbModel", b =>
                {
                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.Property<int>("ShelfId")
                        .HasColumnType("int");

                    b.HasKey("LibraryId", "ShelfId");

                    b.HasIndex("ShelfId");

                    b.ToTable("LibraryShelves");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_OwnerDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("DefaultLibraryGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DefaultShelfGuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_RelatedVersionsDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("RelatedVersions");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ShelfDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<bool>("HasImage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.Property<byte>("_integrityVersion")
                        .HasColumnType("tinyint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Shelves");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ShelfDocument_DbModel", b =>
                {
                    b.Property<int>("ShelfId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.HasKey("ShelfId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("ShelfDocuments");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_TagDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_UserFavoriteDocument_DbModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "DocumentId");

                    b.HasIndex("DocumentId");

                    b.ToTable("UserFavoriteDocuments");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_UserFavoriteLibrary_DbModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("LibraryId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "LibraryId");

                    b.HasIndex("LibraryId");

                    b.ToTable("UserFavoriteLibraries");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_UserFavoriteShelf_DbModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ShelfId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ShelfId");

                    b.HasIndex("ShelfId");

                    b.ToTable("UserFavoriteShelves");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_DocumentDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "Owner")
                        .WithMany("Documents")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_RelatedVersionsDbModel", "RelatedVersions")
                        .WithMany("Documents")
                        .HasForeignKey("RelatedVersionsId");

                    b.Navigation("Owner");

                    b.Navigation("RelatedVersions");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_DocumentTag_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_DocumentDbModel", "Document")
                        .WithMany("Tags")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_TagDbModel", "Tag")
                        .WithMany("Documents")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ElementDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "Owner")
                        .WithMany("Elements")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_DocumentDbModel", "ParentDocument")
                        .WithMany("Elements")
                        .HasForeignKey("ParentDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ParentDocument");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_FollowerFollowing_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "Follower")
                        .WithMany("Followings")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "Following")
                        .WithMany("Followers")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_LibraryDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "Owner")
                        .WithMany("Libraries")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_LibraryShelf_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_LibraryDbModel", "Library")
                        .WithMany("Shelves")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_ShelfDbModel", "Shelf")
                        .WithMany("ParentLibraries")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ShelfDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "Owner")
                        .WithMany("Shelves")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ShelfDocument_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_DocumentDbModel", "Document")
                        .WithMany("ParentShelves")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_ShelfDbModel", "Shelf")
                        .WithMany("Documents")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Shelf");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_UserFavoriteDocument_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_DocumentDbModel", "Document")
                        .WithMany("InFavorOf")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "User")
                        .WithMany("FavoriteDocuments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_UserFavoriteLibrary_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_LibraryDbModel", "Library")
                        .WithMany("InFavorOf")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "User")
                        .WithMany("FavoriteLibraries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_UserFavoriteShelf_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Library_ShelfDbModel", "Shelf")
                        .WithMany("InFavorOf")
                        .HasForeignKey("ShelfId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Library_OwnerDbModel", "User")
                        .WithMany("FavoriteShelves")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shelf");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_DocumentDbModel", b =>
                {
                    b.Navigation("Elements");

                    b.Navigation("InFavorOf");

                    b.Navigation("ParentShelves");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_LibraryDbModel", b =>
                {
                    b.Navigation("InFavorOf");

                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_OwnerDbModel", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Elements");

                    b.Navigation("FavoriteDocuments");

                    b.Navigation("FavoriteLibraries");

                    b.Navigation("FavoriteShelves");

                    b.Navigation("Followers");

                    b.Navigation("Followings");

                    b.Navigation("Libraries");

                    b.Navigation("Shelves");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_RelatedVersionsDbModel", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_ShelfDbModel", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("InFavorOf");

                    b.Navigation("ParentLibraries");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Library_TagDbModel", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
