// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using holibz.Models;

#nullable disable

namespace holibz.Migrations.WebComponents_Db
{
    [DbContext(typeof(WebComponents_DbContext))]
    partial class WebComponents_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebComponents_ItemDbModelWebComponents_TagDbModel", b =>
                {
                    b.Property<int>("ItemDbModelsId")
                        .HasColumnType("int");

                    b.Property<int>("TagDbModelsId")
                        .HasColumnType("int");

                    b.HasKey("ItemDbModelsId", "TagDbModelsId");

                    b.HasIndex("TagDbModelsId");

                    b.ToTable("WebComponents_ItemDbModelWebComponents_TagDbModel");
                });

            modelBuilder.Entity("holibz.Models.WebComponents_ItemDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeveloperGuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("holibz.Models.WebComponents_TagDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("WebComponents_ItemDbModelWebComponents_TagDbModel", b =>
                {
                    b.HasOne("holibz.Models.WebComponents_ItemDbModel", null)
                        .WithMany()
                        .HasForeignKey("ItemDbModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("holibz.Models.WebComponents_TagDbModel", null)
                        .WithMany()
                        .HasForeignKey("TagDbModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
