// <auto-generated />
using System;
using AspNetCoreApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore.Migrations.Review_Db
{
    [DbContext(typeof(Review_DbContext))]
    [Migration("20251211064906_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreApp.Models.Review_CommentDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ParentReviewId")
                        .HasColumnType("int");

                    b.Property<int?>("ReplyToId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WriterGuid")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("_thumbsDownBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("_thumbsUpBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("ParentReviewId");

                    b.HasIndex("ReplyToId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_ReviewDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SubjectGuid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubjectOwnerGuid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("_likedByGuids")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SubjectGuid")
                        .IsUnique();

                    b.HasIndex("SubjectOwnerGuid");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_CommentDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_ReviewDbModel", "ParentReview")
                        .WithMany("Comments")
                        .HasForeignKey("ParentReviewId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCoreApp.Models.Review_CommentDbModel", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentReview");

                    b.Navigation("ReplyTo");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_CommentDbModel", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_ReviewDbModel", b =>
                {
                    b.Navigation("Comments");
                });
#pragma warning restore 612, 618
        }
    }
}
