// <auto-generated />
using System;
using AspNetCoreApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore.Migrations.Review_Db
{
    [DbContext(typeof(Review_DbContext))]
    [Migration("20251219151438_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreApp.Models.Review_CommentDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ParentReviewId")
                        .HasColumnType("int");

                    b.Property<int?>("ReplyToId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("ParentReviewId");

                    b.HasIndex("ReplyToId");

                    b.HasIndex("WriterId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_ReviewDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<string>("SubjectGuid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SubjectGuid")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_UserDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Guid")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Review_CommentDbModelReview_UserDbModel", b =>
                {
                    b.Property<int>("ThumbsUpsId")
                        .HasColumnType("int");

                    b.Property<int>("ThumbsUpsId1")
                        .HasColumnType("int");

                    b.HasKey("ThumbsUpsId", "ThumbsUpsId1");

                    b.HasIndex("ThumbsUpsId1");

                    b.ToTable("Review_CommentDbModelReview_UserDbModel");
                });

            modelBuilder.Entity("Review_CommentDbModelReview_UserDbModel1", b =>
                {
                    b.Property<int>("ThumbsDownsId")
                        .HasColumnType("int");

                    b.Property<int>("ThumbsDownsId1")
                        .HasColumnType("int");

                    b.HasKey("ThumbsDownsId", "ThumbsDownsId1");

                    b.HasIndex("ThumbsDownsId1");

                    b.ToTable("Review_CommentDbModelReview_UserDbModel1");
                });

            modelBuilder.Entity("Review_ReviewDbModelReview_UserDbModel", b =>
                {
                    b.Property<int>("LikesId")
                        .HasColumnType("int");

                    b.Property<int>("LikesId1")
                        .HasColumnType("int");

                    b.HasKey("LikesId", "LikesId1");

                    b.HasIndex("LikesId1");

                    b.ToTable("Review_ReviewDbModelReview_UserDbModel");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_CommentDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_ReviewDbModel", "ParentReview")
                        .WithMany("Comments")
                        .HasForeignKey("ParentReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Review_CommentDbModel", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", "Writer")
                        .WithMany("Comments")
                        .HasForeignKey("WriterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentReview");

                    b.Navigation("ReplyTo");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_ReviewDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", "Owner")
                        .WithMany("Reviews")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Review_CommentDbModelReview_UserDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", null)
                        .WithMany()
                        .HasForeignKey("ThumbsUpsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Review_CommentDbModel", null)
                        .WithMany()
                        .HasForeignKey("ThumbsUpsId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Review_CommentDbModelReview_UserDbModel1", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", null)
                        .WithMany()
                        .HasForeignKey("ThumbsDownsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Review_CommentDbModel", null)
                        .WithMany()
                        .HasForeignKey("ThumbsDownsId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Review_ReviewDbModelReview_UserDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_ReviewDbModel", null)
                        .WithMany()
                        .HasForeignKey("LikesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", null)
                        .WithMany()
                        .HasForeignKey("LikesId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_CommentDbModel", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_ReviewDbModel", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_UserDbModel", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
