// <auto-generated />
using System;
using AspNetCoreApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCore.Migrations.Review_Db
{
    [DbContext(typeof(Review_DbContext))]
    [Migration("20260101171243_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AspNetCoreApp.Models.Review_CommentDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<int>("ParentReviewId")
                        .HasColumnType("int");

                    b.Property<int?>("ReplyToId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("WriterId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("ParentReviewId");

                    b.HasIndex("ReplyToId");

                    b.HasIndex("WriterId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_FollowerFollowing_DbModel", b =>
                {
                    b.Property<int>("FollowerId")
                        .HasColumnType("int");

                    b.Property<int>("FollowingId")
                        .HasColumnType("int");

                    b.HasKey("FollowerId", "FollowingId");

                    b.HasIndex("FollowingId");

                    b.ToTable("FollowerFollowings");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_ReviewDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<Guid>("SubjectGuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("SubjectGuid")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_UserDbModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("char(36)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.HasIndex("Guid")
                        .IsUnique();

                    b.HasIndex("NormalizedUserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_UserLike_DbModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ReviewId");

                    b.HasIndex("ReviewId");

                    b.ToTable("UserLikes");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_UserThumbsDown_DbModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("UserThumbsDown");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_UserThumbsUp_DbModel", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "CommentId");

                    b.HasIndex("CommentId");

                    b.ToTable("UserThumbsUp");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_CommentDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_ReviewDbModel", "ParentReview")
                        .WithMany("Comments")
                        .HasForeignKey("ParentReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Review_CommentDbModel", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", "Writer")
                        .WithMany("GiveComments")
                        .HasForeignKey("WriterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentReview");

                    b.Navigation("ReplyTo");

                    b.Navigation("Writer");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_FollowerFollowing_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", "Follower")
                        .WithMany("Followers")
                        .HasForeignKey("FollowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", "Following")
                        .WithMany("Followings")
                        .HasForeignKey("FollowingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Follower");

                    b.Navigation("Following");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_ReviewDbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", "Owner")
                        .WithMany("GotReviews")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_UserLike_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_ReviewDbModel", "Review")
                        .WithMany("LikedBy")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", "User")
                        .WithMany("GiveLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_UserThumbsDown_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_CommentDbModel", "Comment")
                        .WithMany("ThumbsDownsBy")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", "User")
                        .WithMany("GiveThumbsDowns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_UserThumbsUp_DbModel", b =>
                {
                    b.HasOne("AspNetCoreApp.Models.Review_CommentDbModel", "Comment")
                        .WithMany("ThumbsUpsBy")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AspNetCoreApp.Models.Review_UserDbModel", "User")
                        .WithMany("GiveThumbsUps")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_CommentDbModel", b =>
                {
                    b.Navigation("Replies");

                    b.Navigation("ThumbsDownsBy");

                    b.Navigation("ThumbsUpsBy");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_ReviewDbModel", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("LikedBy");
                });

            modelBuilder.Entity("AspNetCoreApp.Models.Review_UserDbModel", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Followings");

                    b.Navigation("GiveComments");

                    b.Navigation("GiveLikes");

                    b.Navigation("GiveThumbsDowns");

                    b.Navigation("GiveThumbsUps");

                    b.Navigation("GotReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
